### ISSUE TITLE
Replace constants with erlang macros

### ISSUE THREAD

**Issue by mbSmaga** [lambdaacademy/2016.04_erlang_xmpp_ofc#12]
I think we should avoid using constants in the code. For example "0" and "30" in [simple_ids_switch](https://github.com/lambdaacademy/2016.04_erlang_xmpp_ofc/blob/master/src/xmpp_ofc_simple_ids_switch.erl):

``` erlang
...
FlowOpts = [{table_id, 0}, {priority, ?FLOW_PRIORITY}, 
            {idle_timeout, 30},
...
```

For more readable code, I think we should replace this with something meaningful like e.g.:

``` erlang
...
FlowOpts = [{table_id, ?DEFAULT_FLOW_TABLE_ID}, {priority, ?FLOW_PRIORITY}, 
            {idle_timeout, ?FM_TIMEOUT_S(idle)},
...
```

**Comment by mentels** [comment]
Definately
