### ISSUE TITLE
Init Flow from Simple IDS timeouts permanently after idle timeout

### ISSUE THREAD

**Issue by mentels** [lambdaacademy/2016.04_erlang_xmpp_ofc#16]
Look here: https://github.com/lambdaacademy/2016.04_erlang_xmpp_ofc/blob/master/src/xmpp_ofc_simple_ids_switch.erl#L135

After all the clients are served by their own `FlowMods` this Flow Entry times out. Then, when any of the is blocked, after unblocking there's no `FlowEntry` capturing the XMPP traffic.

**Comment by mbSmaga** [comment]
Woa! Made mistake while replacing constants with values... Fixing it right away.
