### ISSUE TITLE
Improve a Controller Module API regarding sending OF messages

### ISSUE THREAD

**Issue by mentels** [lambdaacademy/2016.04_erlang_xmpp_ofc#2]
## API that allows delayed messages

We want an API like:

``` erlang
-spec handle_message(Pid::pid(),
                     Msg::{MsgType :: term(),
                           Xid :: term(),
                           MsgBody :: [tuple()]},
                     OFMessages) -> OFMessages when
      OFMessages :: [ofp_message() |
                     {Timeout :: non_neg_integer(), ofp_message()}].
handle_message(Pid, Msg, OFMessages) ->
    gen_server:call(Pid, {handle_message, Msg, OFMessages}).
```

The  `{Timeout :: non_neg_integer(), ofp_message()}` indicates a message that should be send to the controller after `Timeout` milliseconds.
## API that allows immediate messages

The `xmpp_ofc_gen_switch` should pass its Pid to a Controller module so that it can send messages directly to it that are to be send to the controller immediately. A Controller Module start function should look like this:

``` erlang
-spec start_link(binary(), pid()) -> {ok, pid()} | ignore | {error, term()}.
start_link(DatapathId, ParentPid) ->
    {ok, Pid} = gen_server:start_link(?MODULE, [DatapathId, ParentPid], []),
    {ok, Pid, subscriptions(), [init_flow_mod()]}.
```

Then that `ParentPid` could be used by the CM as follows:

``` erlang
ParentPid ! {of_send, {DatapathId, OFMessages}}
```

However, if the switch sends any replies they should be handled within the bounds of the subscriptions mechanism, i.e. the CM has to explicitly subscribe to OF messages upon start.

**Comment by mbSmaga** [comment]
Hey Guys,

If the issue is still free I'll take care of it :smiley:

**Comment by mentels** [comment]
It IS free.
